train_file: [
            'datasets/train/cc3m_train_hierarchical_label.jsonl',
             ]
image_path_root: ""

vit: 'swin_l'
vit_grad_ckpt: False
vit_ckpt_layer: 0

image_size: 224
batch_size: 80 

# optimizer
weight_decay: 0.05
init_lr: 1e-4
min_lr: 5e-7
warmup_lr: 5e-7
lr_decay_rate: 0.9 
max_epoch: 10
warmup_steps: 3000

class_num: 3334

embed_dim: 512
curv_init: -2.3026 
learn_curv: True
entail_weight: 10 
logit_scale: 2.6593